title: Generation of a Maxwellian distribution of electrons.
author: Jaswant Panchumarti
email: jaswantphysx@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
   This page contains information on how random velocities are assigned to the electrons such that it is described
   by a Maxwellian.
  
github_username:  jaswantp

plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: jekyll-theme-dinky
